DAPA-22 Automate version increment before merging to main and expose version in API and docs
Integrate versioning system and automate version bumps

Added a `version.py` file to define app version and updated FastAPI title and version to use it. Implemented a GitHub Actions workflow step to automatically bump patch version and push changes to the main branch after a successful build.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,11 +58,15 @@ jobs:
   
             FILE="version.py"
   
-            VERSION=$(grep -oP '__version__\s*=\s*"\K[0-9]+\.[0-9]+\.[0-9]+' "$FILE")
+            VERSION=$(grep -oP '__version__\s*=\s*"\K[0-9]\.[0-9]\.[0-9]' "$FILE")
+            if [ -z "$VERSION" ]; then
+              echo "Error: Could not extract version from $FILE"
+              exit 1
+            fi
   
             IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
   
-            PATCH=$((PATCH + 1))
+            PATCH=$((PATCH  + 1))
   
             NEW_VERSION="$MAJOR.$MINOR.$PATCH"
   
